name: test

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        rust: [stable, 1.43]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Install dependencies
        run: sudo apt-get install gcc patch libudev-dev git

      - uses: actions/checkout@v2
      - uses: dtolnay/rust-toolchain@${{ matrix.rust }}

      - name: Init submodules
        run: git submodule update --init

      - name: Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-${{ matrix.rust }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Run tests
        run: cargo test --verbose
